.apex/unpackaged/objects/scormanywhere__Course__c.object
<CustomObject>
    <fields>
        <fullName>scormanywhere__SCORM_Training_Type__c</fullName>
        <label>SCORM Training Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

.apex/unpackaged/objects/scormanywhere__Related_Media__c.object
<CustomObject>
    <fields>
        <fullName>scormanywhere__Course__c</fullName>
        <label>Media</label>
        <referenceTo>scormanywhere__Course__c</referenceTo>
        <relationshipLabel>Related Media</relationshipLabel>
        <relationshipName>Related_Media</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>scormanywhere__Object_Id__c</fullName>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Related Media</label>
    <nameField>
        <displayFormat>RMN-{0}</displayFormat>
        <label>Related Media Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/TestRelatedMediaCmpCtrl.cls
@isTest
private class TestRelatedMediaCmpCtrl {

    @isTest static void testGetMedia() {
        Case newCase = new Case();
        insert newCase;
        scormanywhere__Course__c course = new scormanywhere__Course__c(Name='Test3',scormanywhere__SCORM_Training_Type__c='mkv');
        insert course;
        scormanywhere__Related_Media__c newMedia = new scormanywhere__Related_Media__c(scormanywhere__Course__c = course.Id, scormanywhere__Object_Id__c = newCase.Id);
        insert newMedia;

        System.assertEquals(1, RelatedMediaCmpCtrl.getContent(newCase.Id).size());
        System.assert(RelatedMediaCmpCtrl.getLink(course.Id) != null);
    }
}