.apex/unpackaged/objects/scormanywhere__Course__c.object
<CustomObject>
    <fields>
        <fullName>scormanywhere__SCORM_Training_Type__c</fullName>
        <label>SCORM Training Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>scormanywhere__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

.apex/unpackaged/objects/scormanywhere__Transcript__c.object
<CustomObject>
    <fields>
        <fullName>scormanywhere__Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Media</label>
        <referenceTo>scormanywhere__Course__c</referenceTo>
        <relationshipLabel>Transcripts</relationshipLabel>
        <relationshipName>Transcripts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>scormanywhere__Status__c</fullName>
        <formula>IF (AND(scormanywhere__SCORM_Progress_Status__c == false,  scormanywhere__SCORM_Satisfied_Status__c == false, scormanywhere__SCORM_Attempt_Completion_Status__c == false,  scormanywhere__SCORM_Attempt_Progress_Status__c == false),
NULL,
IF ( 
 AND(scormanywhere__SCORM_Progress_Status__c == true,  scormanywhere__SCORM_Satisfied_Status__c == false ), 
  &apos;Failed&apos;, 
  IF(
    OR(
     AND(scormanywhere__SCORM_Progress_Status__c == false,  scormanywhere__SCORM_Satisfied_Status__c == false,  scormanywhere__SCORM_Attempt_Completion_Status__c == false,  scormanywhere__SCORM_Attempt_Progress_Status__c == true),
     AND(scormanywhere__SCORM_Attempt_Completion_Status__c == false,  scormanywhere__SCORM_Attempt_Progress_Status__c == false)
    ),
    &apos;Incomplete&apos;,
      IF(AND(scormanywhere__SCORM_Progress_Status__c == true,  scormanywhere__SCORM_Satisfied_Status__c == true), 
      &apos;Passed&apos;, 
        IF(AND(scormanywhere__SCORM_Progress_Status__c == false,  scormanywhere__SCORM_Satisfied_Status__c == false, scormanywhere__SCORM_Attempt_Completion_Status__c == true,  scormanywhere__SCORM_Attempt_Progress_Status__c == true),
        &apos;Completed&apos;, NULL)
	  )
  )
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>scormanywhere__Test_Launch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Launch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>scormanywhere__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Transcript</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transcript</label>
    <nameField>
        <displayFormat>TRS-{0}</displayFormat>
        <label>Transcript Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcripts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/classes/TestUserMediaCmpCtrl.cls
@isTest
public class TestUserMediaCmpCtrl {

    static testmethod void testMyMedia(){
        List<scormanywhere__Transcript__c> transcripts = new List<scormanywhere__Transcript__c>();
        scormanywhere__Course__c course = new scormanywhere__Course__c(Name='Test3',scormanywhere__SCORM_Training_Type__c='mkv', scormanywhere__Status__c = 'Active');
        insert course;
        scormanywhere__Transcript__c course1 = new scormanywhere__Transcript__c(scormanywhere__Course__c=course.Id,scormanywhere__User__c=UserInfo.getUserId(), scormanywhere__Test_Launch__c = false);
        scormanywhere__Transcript__c course2 = new scormanywhere__Transcript__c(scormanywhere__Course__c=course.Id,scormanywhere__User__c=UserInfo.getUserId(), scormanywhere__Test_Launch__c = false);
        transcripts.add(course1);
        transcripts.add(course2);
        insert transcripts;
        System.assert(UserMediaCmpCtrl.getViewedMedia(UserInfo.getUserId()).size()>1);
        System.assert(UserMediaCmpCtrl.getUploadedMedia('').size()>0);
        System.assert(UserMediaCmpCtrl.getPrefix() != null);
        System.assert(UserMediaCmpCtrl.getUserId() != null);
        
        List<String> coursesId = new List<String>();
        coursesId.add(course.Id);
        List<String> transcriptsId = new List<String>();
        transcriptsId.add(transcripts[0].Id);
        transcriptsId.add(transcripts[1].Id);
        
        System.assert(UserMediaCmpCtrl.getCourses(UserInfo.getUserId(), coursesId) != null);
        System.assert(UserMediaCmpCtrl.getTranscripts(transcriptsId) != null);
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        String email = UserInfo.getUserEmail();
        User user = new User(Alias = 'standt', Email=email,
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles', UserName='s1w@testorg.com');
        insert user;
        String currentUser = UserInfo.getUserId();
        System.runAs(user){
            System.assertEquals(1, UserMediaCmpCtrl.getUploadedMedia(currentUser).size());
        }
        System.assert(!String.isBlank(Util.debugInfo('testmsg', 'testmsg', 'testmsg')));
        Util.sendEmail('error', 'subject');
    }
}