.apex/unpackaged/objects/scormanywhere__Course__c.object
<CustomObject>
    <label>Media</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

.apex/unpackaged/objects/scormanywhere__Related_Media__c.object
<CustomObject>
    <fields>
        <fullName>scormanywhere__Course__c</fullName>
        <label>Media</label>
        <referenceTo>scormanywhere__Course__c</referenceTo>
        <relationshipLabel>Related Media</relationshipLabel>
        <relationshipName>Related_Media</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Related Media</label>
    <nameField>
        <displayFormat>RMN-{0}</displayFormat>
        <label>Related Media Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/UploaderCmpCtrl.cls
public class UploaderCmpCtrl {
    @AuraEnabled
    public static UploladParams getUploadParams(){
        UploladParams result = new UploladParams();
        if(!Test.isRunningTest()){
            result.urlForUpload = scormanywhere.ApiService.getLink('UploadApi', null);
            result.urlForGetProgress = scormanywhere.ApiService.getLink('GetProgress', null);
            result.urlForGetStatus = scormanywhere.ApiService.getLink('GetStatus', null);
        } else{
            result.urlForUpload = 'testurl&uploadId=124-234-234&testparam=11111';
            result.urlForGetProgress = 'testprogress';
            result.urlForGetStatus = 'teststatus';
        }
        result.guid = getStringParameterFromURL('uploadId', result.urlForUpload);
        result.guid = result.guid.toLowerCase();
        result.orgId = UserInfo.getOrganizationId();
        result.isUploadMediaAccessible = checkMediaAccess();
        system.debug(result);
        return result;
    }
    
    private static Boolean checkMediaAccess() {
        return scormanywhere__Related_Media__c.sObjectType.getDescribe().isCreateable()
            && scormanywhere__Course__c.sObjectType.getDescribe().isCreateable();
    }
    
    private static String getStringParameterFromURL(String parameterName, String stringUrl) {
        if(!String.isBlank(stringUrl)){
            Map<String, String> paramsByName = new Map<String, String>();
            for(String item : stringUrl.split('&')){
                paramsByName.put(item.substringBefore('='), item.substringAfter('='));
            }
            return paramsByName.get(parameterName);
        }
        return null;
    }
    
    public class UploladParams{
        @AuraEnabled String urlForUpload {get; set;}
        @AuraEnabled String urlForGetProgress {get; set;}
        @AuraEnabled String urlForGetStatus {get; set;}
        @AuraEnabled String orgId {get; set;}
        @AuraEnabled String guid {get; set;}
        @AuraEnabled Boolean isUploadMediaAccessible {get; set;}
    }
}