unpackaged/objects/scormanywhere__Channel__c.object
<CustomObject>
    <fields>
        <fullName>scormanywhere__Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Channel</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Channel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/scormanywhere__Channel_Course__c.object
<CustomObject>
    <fields>
        <fullName>scormanywhere__Channel__c</fullName>
        <label>Channel</label>
        <referenceTo>scormanywhere__Channel__c</referenceTo>
        <relationshipName>Channels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Channel Media</label>
    <nameField>
        <displayFormat>CCN-{0}</displayFormat>
        <label>Channel Media Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/ChannelWrapper.cls
public with sharing class ChannelWrapper {

    @AuraEnabled public Id id {get; set;}
    @AuraEnabled public String name {get; set;}
    @AuraEnabled public Boolean containsVideo {get; set;}
    @AuraEnabled public Integer countVideo {get; set;}
    @AuraEnabled public String link {get; set;}

    public ChannelWrapper(ChannelWrapper cw) {
        id = cw.Id;
        name = cw.name;
        containsVideo = cw.containsVideo;
        countVideo = cw.countVideo;
    }

    public ChannelWrapper(scormanywhere__Channel__c channel) {
        id = channel.Id;
        name = channel.scormanywhere__Title__c;
        countVideo = channel.scormanywhere__Channels__r.size();
        link = '';
        if (!Test.isRunningTest()) {
        	String temp = Network.getLoginUrl(Network.getNetworkId());
            if (temp != null) {
            	link += temp.removeEnd(temp.substringAfterLast('/')).removeEnd('/');
            }
        }
        link += '/catalog-content#:' + channel.Id;
    }
}